name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd project
          git clone git@github.com:mfaishal882/deploy-prj.git
          docker stop deploy-prj
          docker rm deploy-prj
          docker build -t deploy-prj .
          docker run --name prjku -d -p 8000:8000 deploy-prj
